### ISSUE TITLE
Strategy section need to be change

### ISSUE THREAD

**Issue by orvi2014** [orvi2014/oa#10]

**Comment by lordofxtreme** [comment]
needs content

**Comment by Himadri001** [comment]
Where is the strategy section.. There are no strategy section in the homepage.

**Comment by orvi2014** [comment]
Himadri, check the strategy div under services section.

**Comment by Himadri001** [comment]
Can someone explain me what strategy and analytic  under services. Like are we giving analytic software products also?

**Comment by orvi2014** [comment]
this issue is resolved under #20
