### ISSUE TITLE
Add Different words to animation

### ISSUE THREAD

**Issue by orvi2014** [orvi2014/oa#5]

**Comment by orvi2014** [comment]
Demo Link: 

1. https://codepen.io/JordanC/pen/gkhzK 

What you have to focus here how html id link with css. In my code, I basically span that part. You may not need span now.

**Comment by lordofxtreme** [comment]
need other words

**Comment by orvi2014** [comment]
Test with different words first. We will provide you the different words.

**Comment by orvi2014** [comment]
This issue is resolved in #19 PR
